In [19]:
import json
from pathlib import Path

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [20]:
RAW_PATH = Path("../data/raw/historical_weather/ia_hourly_weather_2015-01.parquet")


weather = pd.read_parquet(RAW_PATH)

In [21]:
weather.head()

,time,county_fips,county_name,latitude,longitude,temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,precipitation,weather_code,wind_direction_10m
0,2015-01-01 00:00:00-06:00,19001,Adair,41.328528,-94.478164,13.225101,56.001431,1026.400024,13.542628,0.0,3.0,247.671295
1,2015-01-01 01:00:00-06:00,19001,Adair,41.328528,-94.478164,13.135099,57.660507,1025.599976,13.016956,0.0,3.0,250.942200
2,2015-01-01 02:00:00-06:00,19001,Adair,41.328528,-94.478164,12.685101,58.077881,1024.599976,12.338023,0.0,3.0,247.619812
3,2015-01-01 03:00:00-06:00,19001,Adair,41.328528,-94.478164,12.415100,56.586411,1024.000000,12.805725,0.0,3.0,242.987411
4,2015-01-01 04:00:00-06:00,19001,Adair,41.328528,-94.478164,12.505100,64.187523,1024.000000,13.302158,0.0,3.0,250.346085

In [22]:
weather["date"] = (
    pd.to_datetime(weather["time"], unit="ms")
    .dt.date 
)


weather["time"] = pd.to_datetime(
    weather["time"],
    unit="ms"
)

In [23]:
weather.head()

,time,county_fips,county_name,latitude,longitude,temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,precipitation,weather_code,wind_direction_10m,date
0,2015-01-01 00:00:00-06:00,19001,Adair,41.328528,-94.478164,13.225101,56.001431,1026.400024,13.542628,0.0,3.0,247.671295,2015-01-01
1,2015-01-01 01:00:00-06:00,19001,Adair,41.328528,-94.478164,13.135099,57.660507,1025.599976,13.016956,0.0,3.0,250.942200,2015-01-01
2,2015-01-01 02:00:00-06:00,19001,Adair,41.328528,-94.478164,12.685101,58.077881,1024.599976,12.338023,0.0,3.0,247.619812,2015-01-01
3,2015-01-01 03:00:00-06:00,19001,Adair,41.328528,-94.478164,12.415100,56.586411,1024.000000,12.805725,0.0,3.0,242.987411,2015-01-01
4,2015-01-01 04:00:00-06:00,19001,Adair,41.328528,-94.478164,12.505100,64.187523,1024.000000,13.302158,0.0,3.0,250.346085,2015-01-01

In [28]:
weather.describe()

,latitude,longitude,temperature_2m,relative_humidity_2m,pressure_msl,wind_speed_10m,precipitation,weather_code,wind_direction_10m
count,73656.000000,73656.000000,73656.000000,73656.000000,73656.000000,73656.000000,73656.000000,73656.000000,73656.000000
mean,42.029902,-93.466102,23.449080,74.634224,1023.643738,9.544981,0.001392,6.960533,231.853592
std,0.844564,1.555353,14.411480,12.038428,10.892551,4.515791,0.006653,18.454729,89.923454
min,40.647588,-96.215973,-22.539997,23.154642,1001.200012,0.000000,0.000000,0.000000,0.763880
25%,41.330622,-94.697108,13.056801,67.172661,1015.400024,6.109918,0.000000,0.000000,182.489502
50%,42.042513,-93.466093,27.431149,75.711288,1022.400024,8.750073,0.000000,2.000000,248.749420
75%,42.741522,-92.167721,33.824299,83.660025,1031.300049,12.311632,0.000000,3.000000,304.114502
max,43.389611,-90.534243,66.002899,100.000000,1057.900024,27.588659,0.078740,75.000000,360.000000

In [25]:
weather.shape

(73656, 13)

In [26]:
weather.columns

Index(['time', 'county_fips', 'county_name', 'latitude', 'longitude',
       'temperature_2m', 'relative_humidity_2m', 'pressure_msl',
       'wind_speed_10m', 'precipitation', 'weather_code', 'wind_direction_10m',
       'date'],
      dtype='str')

In [30]:
print(
    "Time and County unique:",
    not weather[["time", "county_name"]].duplicated().any()
)

print(
    "Duplicated Time and Counties:",
    weather[["time", "county_name"]].duplicated().sum()
)

Time and County unique: True
Duplicated Time and Counties: 0

In [31]:
print(weather.isna().sum())
print(
    (
        (weather["county_fips"] == 0)
        & weather["county_name"].isna()
    ).sum()
)

time                    0
county_fips             0
county_name             0
latitude                0
longitude               0
temperature_2m          0
relative_humidity_2m    0
pressure_msl            0
wind_speed_10m          0
precipitation           0
weather_code            0
wind_direction_10m      0
date                    0
dtype: int64
0